# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41e8033d6bb5a024c60a0b871e8b44e05cdd3824fb396e2f80cc34491749e92b780e12471023442c48c22e9903d94689f9d9ac4b4fa047345cd424daf2f039b6

test:
  secret_key_base: 0d3ead674eda5d89db15d8fc785d05ec70416f642ce77790090358e5f1e703a11add8954027b06403f948c4d4275506ce29fad07c4f605104a7137b31a803e70

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
